// Code generated by protoc-gen-go.
// source: registry.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	registry.proto

It has these top-level messages:
	Channel
	PackageName
	Package
	Bundle
	ChannelEntry
	ListPackageRequest
	GetPackageRequest
	GetBundleRequest
	GetBundleInChannelRequest
	GetAllReplacementsRequest
	GetReplacementRequest
	GetAllProvidersRequest
	GetLatestProvidersRequest
	GetDefaultProviderRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Channel struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CsvName string `protobuf:"bytes,2,opt,name=csvName" json:"csvName,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type PackageName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PackageName) Reset()                    { *m = PackageName{} }
func (m *PackageName) String() string            { return proto.CompactTextString(m) }
func (*PackageName) ProtoMessage()               {}
func (*PackageName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PackageName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Package struct {
	Name               string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Channels           []*Channel `protobuf:"bytes,2,rep,name=channels" json:"channels,omitempty"`
	DefaultChannelName string     `protobuf:"bytes,3,opt,name=defaultChannelName" json:"defaultChannelName,omitempty"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Package) GetDefaultChannelName() string {
	if m != nil {
		return m.DefaultChannelName
	}
	return ""
}

type Bundle struct {
	CsvName string   `protobuf:"bytes,1,opt,name=csvName" json:"csvName,omitempty"`
	CsvJson string   `protobuf:"bytes,2,opt,name=csvJson" json:"csvJson,omitempty"`
	Object  []string `protobuf:"bytes,3,rep,name=object" json:"object,omitempty"`
}

func (m *Bundle) Reset()                    { *m = Bundle{} }
func (m *Bundle) String() string            { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()               {}
func (*Bundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Bundle) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

func (m *Bundle) GetCsvJson() string {
	if m != nil {
		return m.CsvJson
	}
	return ""
}

func (m *Bundle) GetObject() []string {
	if m != nil {
		return m.Object
	}
	return nil
}

type ChannelEntry struct {
	PackageName string `protobuf:"bytes,1,opt,name=packageName" json:"packageName,omitempty"`
	ChannelName string `protobuf:"bytes,2,opt,name=channelName" json:"channelName,omitempty"`
	BundleName  string `protobuf:"bytes,3,opt,name=bundleName" json:"bundleName,omitempty"`
	Replaces    string `protobuf:"bytes,4,opt,name=replaces" json:"replaces,omitempty"`
}

func (m *ChannelEntry) Reset()                    { *m = ChannelEntry{} }
func (m *ChannelEntry) String() string            { return proto.CompactTextString(m) }
func (*ChannelEntry) ProtoMessage()               {}
func (*ChannelEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChannelEntry) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ChannelEntry) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ChannelEntry) GetBundleName() string {
	if m != nil {
		return m.BundleName
	}
	return ""
}

func (m *ChannelEntry) GetReplaces() string {
	if m != nil {
		return m.Replaces
	}
	return ""
}

type ListPackageRequest struct {
}

func (m *ListPackageRequest) Reset()                    { *m = ListPackageRequest{} }
func (m *ListPackageRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPackageRequest) ProtoMessage()               {}
func (*ListPackageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetPackageRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetPackageRequest) Reset()                    { *m = GetPackageRequest{} }
func (m *GetPackageRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPackageRequest) ProtoMessage()               {}
func (*GetPackageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetPackageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBundleRequest struct {
	CsvName string `protobuf:"bytes,1,opt,name=csvName" json:"csvName,omitempty"`
}

func (m *GetBundleRequest) Reset()                    { *m = GetBundleRequest{} }
func (m *GetBundleRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBundleRequest) ProtoMessage()               {}
func (*GetBundleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBundleRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type GetBundleInChannelRequest struct {
	PkgName     string `protobuf:"bytes,1,opt,name=pkgName" json:"pkgName,omitempty"`
	ChannelName string `protobuf:"bytes,2,opt,name=channelName" json:"channelName,omitempty"`
}

func (m *GetBundleInChannelRequest) Reset()                    { *m = GetBundleInChannelRequest{} }
func (m *GetBundleInChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBundleInChannelRequest) ProtoMessage()               {}
func (*GetBundleInChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetBundleInChannelRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetBundleInChannelRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type GetAllReplacementsRequest struct {
	CsvName string `protobuf:"bytes,1,opt,name=csvName" json:"csvName,omitempty"`
}

func (m *GetAllReplacementsRequest) Reset()                    { *m = GetAllReplacementsRequest{} }
func (m *GetAllReplacementsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllReplacementsRequest) ProtoMessage()               {}
func (*GetAllReplacementsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetAllReplacementsRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type GetReplacementRequest struct {
	CsvName     string `protobuf:"bytes,1,opt,name=csvName" json:"csvName,omitempty"`
	PkgName     string `protobuf:"bytes,2,opt,name=pkgName" json:"pkgName,omitempty"`
	ChannelName string `protobuf:"bytes,3,opt,name=channelName" json:"channelName,omitempty"`
}

func (m *GetReplacementRequest) Reset()                    { *m = GetReplacementRequest{} }
func (m *GetReplacementRequest) String() string            { return proto.CompactTextString(m) }
func (*GetReplacementRequest) ProtoMessage()               {}
func (*GetReplacementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetReplacementRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

func (m *GetReplacementRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetReplacementRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type GetAllProvidersRequest struct {
	GroupOrName string `protobuf:"bytes,1,opt,name=groupOrName" json:"groupOrName,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Kind        string `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
}

func (m *GetAllProvidersRequest) Reset()                    { *m = GetAllProvidersRequest{} }
func (m *GetAllProvidersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllProvidersRequest) ProtoMessage()               {}
func (*GetAllProvidersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetAllProvidersRequest) GetGroupOrName() string {
	if m != nil {
		return m.GroupOrName
	}
	return ""
}

func (m *GetAllProvidersRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetAllProvidersRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type GetLatestProvidersRequest struct {
	GroupOrName string `protobuf:"bytes,1,opt,name=groupOrName" json:"groupOrName,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Kind        string `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
}

func (m *GetLatestProvidersRequest) Reset()                    { *m = GetLatestProvidersRequest{} }
func (m *GetLatestProvidersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestProvidersRequest) ProtoMessage()               {}
func (*GetLatestProvidersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetLatestProvidersRequest) GetGroupOrName() string {
	if m != nil {
		return m.GroupOrName
	}
	return ""
}

func (m *GetLatestProvidersRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetLatestProvidersRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type GetDefaultProviderRequest struct {
	GroupOrName string `protobuf:"bytes,1,opt,name=groupOrName" json:"groupOrName,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Kind        string `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
}

func (m *GetDefaultProviderRequest) Reset()                    { *m = GetDefaultProviderRequest{} }
func (m *GetDefaultProviderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDefaultProviderRequest) ProtoMessage()               {}
func (*GetDefaultProviderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetDefaultProviderRequest) GetGroupOrName() string {
	if m != nil {
		return m.GroupOrName
	}
	return ""
}

func (m *GetDefaultProviderRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetDefaultProviderRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*Channel)(nil), "api.Channel")
	proto.RegisterType((*PackageName)(nil), "api.PackageName")
	proto.RegisterType((*Package)(nil), "api.Package")
	proto.RegisterType((*Bundle)(nil), "api.Bundle")
	proto.RegisterType((*ChannelEntry)(nil), "api.ChannelEntry")
	proto.RegisterType((*ListPackageRequest)(nil), "api.ListPackageRequest")
	proto.RegisterType((*GetPackageRequest)(nil), "api.GetPackageRequest")
	proto.RegisterType((*GetBundleRequest)(nil), "api.GetBundleRequest")
	proto.RegisterType((*GetBundleInChannelRequest)(nil), "api.GetBundleInChannelRequest")
	proto.RegisterType((*GetAllReplacementsRequest)(nil), "api.GetAllReplacementsRequest")
	proto.RegisterType((*GetReplacementRequest)(nil), "api.GetReplacementRequest")
	proto.RegisterType((*GetAllProvidersRequest)(nil), "api.GetAllProvidersRequest")
	proto.RegisterType((*GetLatestProvidersRequest)(nil), "api.GetLatestProvidersRequest")
	proto.RegisterType((*GetDefaultProviderRequest)(nil), "api.GetDefaultProviderRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registry service

type RegistryClient interface {
	ListPackages(ctx context.Context, in *ListPackageRequest, opts ...grpc.CallOption) (Registry_ListPackagesClient, error)
	GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*Package, error)
	GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetBundleForChannel(ctx context.Context, in *GetBundleInChannelRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetChannelEntriesThatReplace(ctx context.Context, in *GetAllReplacementsRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatReplaceClient, error)
	GetBundleThatReplaces(ctx context.Context, in *GetReplacementRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetChannelEntriesThatProvide(ctx context.Context, in *GetAllProvidersRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatProvideClient, error)
	GetLatestChannelEntriesThatProvide(ctx context.Context, in *GetLatestProvidersRequest, opts ...grpc.CallOption) (Registry_GetLatestChannelEntriesThatProvideClient, error)
	GetDefaultBundleThatProvides(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*Bundle, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) ListPackages(ctx context.Context, in *ListPackageRequest, opts ...grpc.CallOption) (Registry_ListPackagesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Registry_serviceDesc.Streams[0], c.cc, "/api.Registry/ListPackages", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryListPackagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_ListPackagesClient interface {
	Recv() (*PackageName, error)
	grpc.ClientStream
}

type registryListPackagesClient struct {
	grpc.ClientStream
}

func (x *registryListPackagesClient) Recv() (*PackageName, error) {
	m := new(PackageName)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*Package, error) {
	out := new(Package)
	err := grpc.Invoke(ctx, "/api.Registry/GetPackage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := grpc.Invoke(ctx, "/api.Registry/GetBundle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetBundleForChannel(ctx context.Context, in *GetBundleInChannelRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := grpc.Invoke(ctx, "/api.Registry/GetBundleForChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetChannelEntriesThatReplace(ctx context.Context, in *GetAllReplacementsRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatReplaceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Registry_serviceDesc.Streams[1], c.cc, "/api.Registry/GetChannelEntriesThatReplace", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetChannelEntriesThatReplaceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetChannelEntriesThatReplaceClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetChannelEntriesThatReplaceClient struct {
	grpc.ClientStream
}

func (x *registryGetChannelEntriesThatReplaceClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetBundleThatReplaces(ctx context.Context, in *GetReplacementRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := grpc.Invoke(ctx, "/api.Registry/GetBundleThatReplaces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetChannelEntriesThatProvide(ctx context.Context, in *GetAllProvidersRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatProvideClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Registry_serviceDesc.Streams[2], c.cc, "/api.Registry/GetChannelEntriesThatProvide", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetChannelEntriesThatProvideClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetChannelEntriesThatProvideClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetChannelEntriesThatProvideClient struct {
	grpc.ClientStream
}

func (x *registryGetChannelEntriesThatProvideClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetLatestChannelEntriesThatProvide(ctx context.Context, in *GetLatestProvidersRequest, opts ...grpc.CallOption) (Registry_GetLatestChannelEntriesThatProvideClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Registry_serviceDesc.Streams[3], c.cc, "/api.Registry/GetLatestChannelEntriesThatProvide", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetLatestChannelEntriesThatProvideClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetLatestChannelEntriesThatProvideClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetLatestChannelEntriesThatProvideClient struct {
	grpc.ClientStream
}

func (x *registryGetLatestChannelEntriesThatProvideClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetDefaultBundleThatProvides(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := grpc.Invoke(ctx, "/api.Registry/GetDefaultBundleThatProvides", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registry service

type RegistryServer interface {
	ListPackages(*ListPackageRequest, Registry_ListPackagesServer) error
	GetPackage(context.Context, *GetPackageRequest) (*Package, error)
	GetBundle(context.Context, *GetBundleRequest) (*Bundle, error)
	GetBundleForChannel(context.Context, *GetBundleInChannelRequest) (*Bundle, error)
	GetChannelEntriesThatReplace(*GetAllReplacementsRequest, Registry_GetChannelEntriesThatReplaceServer) error
	GetBundleThatReplaces(context.Context, *GetReplacementRequest) (*Bundle, error)
	GetChannelEntriesThatProvide(*GetAllProvidersRequest, Registry_GetChannelEntriesThatProvideServer) error
	GetLatestChannelEntriesThatProvide(*GetLatestProvidersRequest, Registry_GetLatestChannelEntriesThatProvideServer) error
	GetDefaultBundleThatProvides(context.Context, *GetDefaultProviderRequest) (*Bundle, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_ListPackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).ListPackages(m, &registryListPackagesServer{stream})
}

type Registry_ListPackagesServer interface {
	Send(*PackageName) error
	grpc.ServerStream
}

type registryListPackagesServer struct {
	grpc.ServerStream
}

func (x *registryListPackagesServer) Send(m *PackageName) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetPackage(ctx, req.(*GetPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundle(ctx, req.(*GetBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetBundleForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleInChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundleForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundleForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundleForChannel(ctx, req.(*GetBundleInChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetChannelEntriesThatReplace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllReplacementsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetChannelEntriesThatReplace(m, &registryGetChannelEntriesThatReplaceServer{stream})
}

type Registry_GetChannelEntriesThatReplaceServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetChannelEntriesThatReplaceServer struct {
	grpc.ServerStream
}

func (x *registryGetChannelEntriesThatReplaceServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetBundleThatReplaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundleThatReplaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundleThatReplaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundleThatReplaces(ctx, req.(*GetReplacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetChannelEntriesThatProvide_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllProvidersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetChannelEntriesThatProvide(m, &registryGetChannelEntriesThatProvideServer{stream})
}

type Registry_GetChannelEntriesThatProvideServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetChannelEntriesThatProvideServer struct {
	grpc.ServerStream
}

func (x *registryGetChannelEntriesThatProvideServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetLatestChannelEntriesThatProvide_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestProvidersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetLatestChannelEntriesThatProvide(m, &registryGetLatestChannelEntriesThatProvideServer{stream})
}

type Registry_GetLatestChannelEntriesThatProvideServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetLatestChannelEntriesThatProvideServer struct {
	grpc.ServerStream
}

func (x *registryGetLatestChannelEntriesThatProvideServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetDefaultBundleThatProvides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetDefaultBundleThatProvides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetDefaultBundleThatProvides",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetDefaultBundleThatProvides(ctx, req.(*GetDefaultProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPackage",
			Handler:    _Registry_GetPackage_Handler,
		},
		{
			MethodName: "GetBundle",
			Handler:    _Registry_GetBundle_Handler,
		},
		{
			MethodName: "GetBundleForChannel",
			Handler:    _Registry_GetBundleForChannel_Handler,
		},
		{
			MethodName: "GetBundleThatReplaces",
			Handler:    _Registry_GetBundleThatReplaces_Handler,
		},
		{
			MethodName: "GetDefaultBundleThatProvides",
			Handler:    _Registry_GetDefaultBundleThatProvides_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPackages",
			Handler:       _Registry_ListPackages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChannelEntriesThatReplace",
			Handler:       _Registry_GetChannelEntriesThatReplace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChannelEntriesThatProvide",
			Handler:       _Registry_GetChannelEntriesThatProvide_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLatestChannelEntriesThatProvide",
			Handler:       _Registry_GetLatestChannelEntriesThatProvide_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "registry.proto",
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x4e, 0xe2, 0x92, 0x9f, 0x49, 0x84, 0xda, 0x81, 0x86, 0x60, 0x50, 0x15, 0xf6, 0x42, 0x0e,
	0x28, 0x82, 0x02, 0xe2, 0xc4, 0x81, 0x52, 0x88, 0x40, 0x05, 0x2a, 0xab, 0x88, 0x03, 0xa7, 0x8d,
	0xb3, 0x24, 0x26, 0x8e, 0x6d, 0x76, 0x37, 0x41, 0x7d, 0x09, 0x2e, 0xbc, 0x30, 0xf2, 0x7a, 0x6d,
	0x6f, 0x1c, 0x9b, 0x9c, 0xe0, 0xe6, 0xf9, 0xff, 0x66, 0xf6, 0x9b, 0x31, 0xdc, 0xe4, 0x6c, 0xee,
	0x09, 0xc9, 0xaf, 0xc7, 0x11, 0x0f, 0x65, 0x88, 0x16, 0x8d, 0x3c, 0xf2, 0x02, 0x5a, 0xaf, 0x17,
	0x34, 0x08, 0x98, 0x8f, 0x08, 0x07, 0x01, 0x5d, 0xb1, 0x41, 0x7d, 0x58, 0x1f, 0x75, 0x1c, 0xf5,
	0x8d, 0x03, 0x68, 0xb9, 0x62, 0xf3, 0x31, 0x56, 0x37, 0x94, 0x3a, 0x15, 0xc9, 0x03, 0xe8, 0x5e,
	0x52, 0x77, 0x49, 0xe7, 0x2c, 0x16, 0xcb, 0x82, 0xc9, 0x4f, 0x68, 0x69, 0x97, 0xd2, 0xdc, 0x23,
	0x68, 0xbb, 0x49, 0x69, 0x31, 0x68, 0x0c, 0xad, 0x51, 0xf7, 0xb4, 0x37, 0xa6, 0x91, 0x37, 0xd6,
	0x78, 0x9c, 0xcc, 0x8a, 0x63, 0xc0, 0x19, 0xfb, 0x46, 0xd7, 0xbe, 0xd4, 0x36, 0x05, 0xc8, 0x52,
	0xb9, 0x4a, 0x2c, 0xe4, 0x0a, 0x9a, 0x67, 0xeb, 0x60, 0xe6, 0x6f, 0xe1, 0xaf, 0x6f, 0xe1, 0xd7,
	0x96, 0xf7, 0x22, 0x0c, 0x8c, 0xce, 0x62, 0x11, 0xfb, 0xd0, 0x0c, 0xa7, 0xdf, 0x99, 0x2b, 0x07,
	0xd6, 0xd0, 0x1a, 0x75, 0x1c, 0x2d, 0x91, 0x5f, 0x75, 0xe8, 0xe9, 0x2a, 0x6f, 0x02, 0xc9, 0xaf,
	0x71, 0x08, 0xdd, 0x28, 0x1f, 0x81, 0x2e, 0x60, 0xaa, 0x62, 0x0f, 0xd7, 0x40, 0x9c, 0x14, 0x32,
	0x55, 0x78, 0x02, 0x30, 0x55, 0x50, 0x8d, 0x96, 0x0c, 0x0d, 0xda, 0xd0, 0xe6, 0x2c, 0xf2, 0xa9,
	0xcb, 0xc4, 0xe0, 0x40, 0x59, 0x33, 0x99, 0xdc, 0x06, 0xbc, 0xf0, 0x84, 0xd4, 0x33, 0x76, 0xd8,
	0x8f, 0x35, 0x13, 0x92, 0x3c, 0x84, 0xa3, 0x09, 0x2b, 0x28, 0x4b, 0x9f, 0xe7, 0x11, 0x1c, 0x4e,
	0x98, 0x4c, 0x06, 0x95, 0xfa, 0x55, 0xce, 0x8b, 0x7c, 0x81, 0xbb, 0x99, 0xf7, 0xbb, 0x20, 0x7d,
	0xa3, 0x3c, 0x2c, 0x5a, 0xce, 0xcd, 0x30, 0x2d, 0xee, 0x9f, 0x00, 0x79, 0xae, 0x12, 0xbf, 0xf2,
	0x7d, 0x27, 0xe9, 0x6b, 0xc5, 0x02, 0x29, 0xf6, 0xe3, 0x59, 0xc1, 0xf1, 0x84, 0x49, 0x23, 0x66,
	0x6f, 0x88, 0x89, 0xb2, 0xf1, 0x57, 0x94, 0xd6, 0x2e, 0xca, 0x05, 0xf4, 0x13, 0x94, 0x97, 0x3c,
	0xdc, 0x78, 0x33, 0xc6, 0x33, 0x88, 0x43, 0xe8, 0xce, 0x79, 0xb8, 0x8e, 0x3e, 0x71, 0x93, 0x05,
	0x86, 0x2a, 0xae, 0xbb, 0x61, 0x5c, 0x78, 0x39, 0xd5, 0xb4, 0x18, 0x3f, 0xcb, 0xd2, 0x0b, 0x66,
	0xba, 0xa0, 0xfa, 0x26, 0x4b, 0x35, 0x8f, 0x0b, 0x2a, 0x99, 0x90, 0xff, 0xa9, 0xd8, 0x79, 0xb2,
	0x42, 0x69, 0xb5, 0x7f, 0x54, 0xec, 0xf4, 0xf7, 0x0d, 0x68, 0x3b, 0xfa, 0x06, 0xe1, 0x4b, 0xe8,
	0x19, 0xe4, 0x15, 0x78, 0x47, 0xed, 0xfe, 0x2e, 0x9f, 0xed, 0x43, 0x65, 0x30, 0x6e, 0x0d, 0xa9,
	0x3d, 0xae, 0xe3, 0x33, 0x80, 0x9c, 0xe5, 0xd8, 0x57, 0x3e, 0x3b, 0xb4, 0xb7, 0x7b, 0x66, 0x2c,
	0xa9, 0xe1, 0x13, 0xe8, 0x64, 0x24, 0xc6, 0xe3, 0x34, 0x68, 0x6b, 0x05, 0xec, 0xae, 0x52, 0x27,
	0x3a, 0x52, 0xc3, 0x73, 0xb8, 0x95, 0xb9, 0xbc, 0x0d, 0x79, 0x7a, 0x2c, 0x4f, 0xb6, 0x83, 0x8b,
	0x1b, 0x51, 0xcc, 0xf2, 0x19, 0xee, 0x4f, 0x98, 0x34, 0xae, 0x87, 0xc7, 0xc4, 0xd5, 0x82, 0xa6,
	0xfc, 0xcd, 0xd3, 0x95, 0xef, 0x81, 0x7d, 0x64, 0x5e, 0x46, 0x75, 0x7d, 0xd4, 0x14, 0xce, 0xd4,
	0x12, 0x24, 0x55, 0x8c, 0x74, 0x02, 0xed, 0x34, 0xdf, 0xee, 0x82, 0x14, 0xa1, 0x39, 0x15, 0xd0,
	0x34, 0x1b, 0xf0, 0x9e, 0x01, 0xad, 0xc8, 0xc7, 0x2a, 0x5c, 0x5f, 0x81, 0x64, 0x1c, 0xae, 0xce,
	0x9c, 0x35, 0x5d, 0x4e, 0xf6, 0xaa, 0xe4, 0x1f, 0x14, 0x60, 0xcd, 0xd9, 0xbc, 0x77, 0x1d, 0x2e,
	0xf2, 0xb4, 0xe5, 0xb4, 0x2e, 0xf4, 0x3f, 0x6d, 0xaa, 0xbf, 0xe1, 0xd3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0x43, 0xca, 0xf2, 0x1f, 0x07, 0x00, 0x00,
}
