// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Channel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CsvName              string   `protobuf:"bytes,2,opt,name=csvName,proto3" json:"csvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type PackageName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageName) Reset()         { *m = PackageName{} }
func (m *PackageName) String() string { return proto.CompactTextString(m) }
func (*PackageName) ProtoMessage()    {}
func (*PackageName) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *PackageName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageName.Unmarshal(m, b)
}
func (m *PackageName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageName.Marshal(b, m, deterministic)
}
func (m *PackageName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageName.Merge(m, src)
}
func (m *PackageName) XXX_Size() int {
	return xxx_messageInfo_PackageName.Size(m)
}
func (m *PackageName) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageName.DiscardUnknown(m)
}

var xxx_messageInfo_PackageName proto.InternalMessageInfo

func (m *PackageName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Package struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Channels             []*Channel `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	DefaultChannelName   string     `protobuf:"bytes,3,opt,name=defaultChannelName,proto3" json:"defaultChannelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Package) GetDefaultChannelName() string {
	if m != nil {
		return m.DefaultChannelName
	}
	return ""
}

type Bundle struct {
	CsvName              string   `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	PackageName          string   `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ChannelName          string   `protobuf:"bytes,3,opt,name=channelName,proto3" json:"channelName,omitempty"`
	CsvJson              string   `protobuf:"bytes,4,opt,name=csvJson,proto3" json:"csvJson,omitempty"`
	Object               []string `protobuf:"bytes,5,rep,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle.Unmarshal(m, b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return xxx_messageInfo_Bundle.Size(m)
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

func (m *Bundle) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *Bundle) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *Bundle) GetCsvJson() string {
	if m != nil {
		return m.CsvJson
	}
	return ""
}

func (m *Bundle) GetObject() []string {
	if m != nil {
		return m.Object
	}
	return nil
}

type BundlePath struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundlePath) Reset()         { *m = BundlePath{} }
func (m *BundlePath) String() string { return proto.CompactTextString(m) }
func (*BundlePath) ProtoMessage()    {}
func (*BundlePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *BundlePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundlePath.Unmarshal(m, b)
}
func (m *BundlePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundlePath.Marshal(b, m, deterministic)
}
func (m *BundlePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundlePath.Merge(m, src)
}
func (m *BundlePath) XXX_Size() int {
	return xxx_messageInfo_BundlePath.Size(m)
}
func (m *BundlePath) XXX_DiscardUnknown() {
	xxx_messageInfo_BundlePath.DiscardUnknown(m)
}

var xxx_messageInfo_BundlePath proto.InternalMessageInfo

func (m *BundlePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ChannelEntry struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	BundleName           string   `protobuf:"bytes,3,opt,name=bundleName,proto3" json:"bundleName,omitempty"`
	Replaces             string   `protobuf:"bytes,4,opt,name=replaces,proto3" json:"replaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelEntry) Reset()         { *m = ChannelEntry{} }
func (m *ChannelEntry) String() string { return proto.CompactTextString(m) }
func (*ChannelEntry) ProtoMessage()    {}
func (*ChannelEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *ChannelEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelEntry.Unmarshal(m, b)
}
func (m *ChannelEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelEntry.Marshal(b, m, deterministic)
}
func (m *ChannelEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelEntry.Merge(m, src)
}
func (m *ChannelEntry) XXX_Size() int {
	return xxx_messageInfo_ChannelEntry.Size(m)
}
func (m *ChannelEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelEntry proto.InternalMessageInfo

func (m *ChannelEntry) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ChannelEntry) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ChannelEntry) GetBundleName() string {
	if m != nil {
		return m.BundleName
	}
	return ""
}

func (m *ChannelEntry) GetReplaces() string {
	if m != nil {
		return m.Replaces
	}
	return ""
}

type ListPackageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPackageRequest) Reset()         { *m = ListPackageRequest{} }
func (m *ListPackageRequest) String() string { return proto.CompactTextString(m) }
func (*ListPackageRequest) ProtoMessage()    {}
func (*ListPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *ListPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPackageRequest.Unmarshal(m, b)
}
func (m *ListPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPackageRequest.Marshal(b, m, deterministic)
}
func (m *ListPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPackageRequest.Merge(m, src)
}
func (m *ListPackageRequest) XXX_Size() int {
	return xxx_messageInfo_ListPackageRequest.Size(m)
}
func (m *ListPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPackageRequest proto.InternalMessageInfo

type GetPackageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackageRequest) Reset()         { *m = GetPackageRequest{} }
func (m *GetPackageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackageRequest) ProtoMessage()    {}
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *GetPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageRequest.Unmarshal(m, b)
}
func (m *GetPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageRequest.Marshal(b, m, deterministic)
}
func (m *GetPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageRequest.Merge(m, src)
}
func (m *GetPackageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackageRequest.Size(m)
}
func (m *GetPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageRequest proto.InternalMessageInfo

func (m *GetPackageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBundleRequest struct {
	PkgName              string   `protobuf:"bytes,1,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	CsvName              string   `protobuf:"bytes,3,opt,name=csvName,proto3" json:"csvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBundleRequest) Reset()         { *m = GetBundleRequest{} }
func (m *GetBundleRequest) String() string { return proto.CompactTextString(m) }
func (*GetBundleRequest) ProtoMessage()    {}
func (*GetBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *GetBundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBundleRequest.Unmarshal(m, b)
}
func (m *GetBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBundleRequest.Marshal(b, m, deterministic)
}
func (m *GetBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBundleRequest.Merge(m, src)
}
func (m *GetBundleRequest) XXX_Size() int {
	return xxx_messageInfo_GetBundleRequest.Size(m)
}
func (m *GetBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBundleRequest proto.InternalMessageInfo

func (m *GetBundleRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetBundleRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *GetBundleRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type GetBundlePathRequest struct {
	PkgName              string   `protobuf:"bytes,1,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	CsvName              string   `protobuf:"bytes,3,opt,name=csvName,proto3" json:"csvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBundlePathRequest) Reset()         { *m = GetBundlePathRequest{} }
func (m *GetBundlePathRequest) String() string { return proto.CompactTextString(m) }
func (*GetBundlePathRequest) ProtoMessage()    {}
func (*GetBundlePathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{9}
}

func (m *GetBundlePathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBundlePathRequest.Unmarshal(m, b)
}
func (m *GetBundlePathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBundlePathRequest.Marshal(b, m, deterministic)
}
func (m *GetBundlePathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBundlePathRequest.Merge(m, src)
}
func (m *GetBundlePathRequest) XXX_Size() int {
	return xxx_messageInfo_GetBundlePathRequest.Size(m)
}
func (m *GetBundlePathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBundlePathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBundlePathRequest proto.InternalMessageInfo

func (m *GetBundlePathRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetBundlePathRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *GetBundlePathRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type GetBundleInChannelRequest struct {
	PkgName              string   `protobuf:"bytes,1,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBundleInChannelRequest) Reset()         { *m = GetBundleInChannelRequest{} }
func (m *GetBundleInChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetBundleInChannelRequest) ProtoMessage()    {}
func (*GetBundleInChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{10}
}

func (m *GetBundleInChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBundleInChannelRequest.Unmarshal(m, b)
}
func (m *GetBundleInChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBundleInChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetBundleInChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBundleInChannelRequest.Merge(m, src)
}
func (m *GetBundleInChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetBundleInChannelRequest.Size(m)
}
func (m *GetBundleInChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBundleInChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBundleInChannelRequest proto.InternalMessageInfo

func (m *GetBundleInChannelRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetBundleInChannelRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type GetAllReplacementsRequest struct {
	CsvName              string   `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllReplacementsRequest) Reset()         { *m = GetAllReplacementsRequest{} }
func (m *GetAllReplacementsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllReplacementsRequest) ProtoMessage()    {}
func (*GetAllReplacementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{11}
}

func (m *GetAllReplacementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllReplacementsRequest.Unmarshal(m, b)
}
func (m *GetAllReplacementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllReplacementsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllReplacementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllReplacementsRequest.Merge(m, src)
}
func (m *GetAllReplacementsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllReplacementsRequest.Size(m)
}
func (m *GetAllReplacementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllReplacementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllReplacementsRequest proto.InternalMessageInfo

func (m *GetAllReplacementsRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

type GetReplacementRequest struct {
	CsvName              string   `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	PkgName              string   `protobuf:"bytes,2,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName          string   `protobuf:"bytes,3,opt,name=channelName,proto3" json:"channelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReplacementRequest) Reset()         { *m = GetReplacementRequest{} }
func (m *GetReplacementRequest) String() string { return proto.CompactTextString(m) }
func (*GetReplacementRequest) ProtoMessage()    {}
func (*GetReplacementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{12}
}

func (m *GetReplacementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplacementRequest.Unmarshal(m, b)
}
func (m *GetReplacementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplacementRequest.Marshal(b, m, deterministic)
}
func (m *GetReplacementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplacementRequest.Merge(m, src)
}
func (m *GetReplacementRequest) XXX_Size() int {
	return xxx_messageInfo_GetReplacementRequest.Size(m)
}
func (m *GetReplacementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplacementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplacementRequest proto.InternalMessageInfo

func (m *GetReplacementRequest) GetCsvName() string {
	if m != nil {
		return m.CsvName
	}
	return ""
}

func (m *GetReplacementRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *GetReplacementRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type GetAllProvidersRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural               string   `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProvidersRequest) Reset()         { *m = GetAllProvidersRequest{} }
func (m *GetAllProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProvidersRequest) ProtoMessage()    {}
func (*GetAllProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{13}
}

func (m *GetAllProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProvidersRequest.Unmarshal(m, b)
}
func (m *GetAllProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProvidersRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProvidersRequest.Merge(m, src)
}
func (m *GetAllProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProvidersRequest.Size(m)
}
func (m *GetAllProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProvidersRequest proto.InternalMessageInfo

func (m *GetAllProvidersRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetAllProvidersRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetAllProvidersRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetAllProvidersRequest) GetPlural() string {
	if m != nil {
		return m.Plural
	}
	return ""
}

type GetLatestProvidersRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural               string   `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestProvidersRequest) Reset()         { *m = GetLatestProvidersRequest{} }
func (m *GetLatestProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestProvidersRequest) ProtoMessage()    {}
func (*GetLatestProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{14}
}

func (m *GetLatestProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestProvidersRequest.Unmarshal(m, b)
}
func (m *GetLatestProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestProvidersRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestProvidersRequest.Merge(m, src)
}
func (m *GetLatestProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestProvidersRequest.Size(m)
}
func (m *GetLatestProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestProvidersRequest proto.InternalMessageInfo

func (m *GetLatestProvidersRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetLatestProvidersRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetLatestProvidersRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetLatestProvidersRequest) GetPlural() string {
	if m != nil {
		return m.Plural
	}
	return ""
}

type GetDefaultProviderRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural               string   `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDefaultProviderRequest) Reset()         { *m = GetDefaultProviderRequest{} }
func (m *GetDefaultProviderRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefaultProviderRequest) ProtoMessage()    {}
func (*GetDefaultProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{15}
}

func (m *GetDefaultProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefaultProviderRequest.Unmarshal(m, b)
}
func (m *GetDefaultProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefaultProviderRequest.Marshal(b, m, deterministic)
}
func (m *GetDefaultProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefaultProviderRequest.Merge(m, src)
}
func (m *GetDefaultProviderRequest) XXX_Size() int {
	return xxx_messageInfo_GetDefaultProviderRequest.Size(m)
}
func (m *GetDefaultProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefaultProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefaultProviderRequest proto.InternalMessageInfo

func (m *GetDefaultProviderRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetDefaultProviderRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetDefaultProviderRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetDefaultProviderRequest) GetPlural() string {
	if m != nil {
		return m.Plural
	}
	return ""
}

func init() {
	proto.RegisterType((*Channel)(nil), "api.Channel")
	proto.RegisterType((*PackageName)(nil), "api.PackageName")
	proto.RegisterType((*Package)(nil), "api.Package")
	proto.RegisterType((*Bundle)(nil), "api.Bundle")
	proto.RegisterType((*BundlePath)(nil), "api.BundlePath")
	proto.RegisterType((*ChannelEntry)(nil), "api.ChannelEntry")
	proto.RegisterType((*ListPackageRequest)(nil), "api.ListPackageRequest")
	proto.RegisterType((*GetPackageRequest)(nil), "api.GetPackageRequest")
	proto.RegisterType((*GetBundleRequest)(nil), "api.GetBundleRequest")
	proto.RegisterType((*GetBundlePathRequest)(nil), "api.GetBundlePathRequest")
	proto.RegisterType((*GetBundleInChannelRequest)(nil), "api.GetBundleInChannelRequest")
	proto.RegisterType((*GetAllReplacementsRequest)(nil), "api.GetAllReplacementsRequest")
	proto.RegisterType((*GetReplacementRequest)(nil), "api.GetReplacementRequest")
	proto.RegisterType((*GetAllProvidersRequest)(nil), "api.GetAllProvidersRequest")
	proto.RegisterType((*GetLatestProvidersRequest)(nil), "api.GetLatestProvidersRequest")
	proto.RegisterType((*GetDefaultProviderRequest)(nil), "api.GetDefaultProviderRequest")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xda, 0xf5, 0xeb, 0xb6, 0xc0, 0x66, 0xba, 0x92, 0x05, 0x34, 0x15, 0xbf, 0xd0, 0xa7,
	0x0a, 0x06, 0x88, 0xa7, 0x3d, 0x30, 0x06, 0x15, 0x68, 0xa0, 0x2a, 0x02, 0xf1, 0xc0, 0x93, 0x9b,
	0x9a, 0x36, 0x34, 0x4d, 0x42, 0xec, 0x76, 0xda, 0x9f, 0xe0, 0x99, 0xdf, 0xc5, 0x2f, 0x42, 0x76,
	0x9c, 0xd4, 0xf9, 0x28, 0x43, 0x42, 0xc0, 0x5b, 0xee, 0xb5, 0xef, 0x39, 0xe7, 0xda, 0xf7, 0xb8,
	0x85, 0x9b, 0x11, 0x9d, 0xbb, 0x8c, 0x47, 0x57, 0xa3, 0x30, 0x0a, 0x78, 0x80, 0x6a, 0x24, 0x74,
	0xf1, 0x33, 0x68, 0xbe, 0x58, 0x10, 0xdf, 0xa7, 0x1e, 0x42, 0xb0, 0xe7, 0x93, 0x15, 0x35, 0x8d,
	0x81, 0x31, 0x6c, 0xdb, 0xf2, 0x1b, 0x99, 0xd0, 0x74, 0xd8, 0xe6, 0x9d, 0x48, 0x57, 0x65, 0x3a,
	0x09, 0xf1, 0x7d, 0xe8, 0x4c, 0x88, 0xb3, 0x24, 0x73, 0x2a, 0xc2, 0xb2, 0x62, 0x7c, 0x09, 0x4d,
	0xb5, 0xa5, 0x14, 0x7b, 0x08, 0x2d, 0x27, 0xa6, 0x66, 0x66, 0x75, 0x50, 0x1b, 0x76, 0x4e, 0xba,
	0x23, 0x12, 0xba, 0x23, 0xa5, 0xc7, 0x4e, 0x57, 0xd1, 0x08, 0xd0, 0x8c, 0x7e, 0x26, 0x6b, 0x8f,
	0xab, 0x35, 0x29, 0xa8, 0x26, 0xb1, 0x4a, 0x56, 0xf0, 0x77, 0x03, 0x1a, 0x67, 0x6b, 0x7f, 0xe6,
	0x65, 0x1a, 0x30, 0x32, 0x0d, 0xa0, 0x01, 0x74, 0xc2, 0x6d, 0x03, 0xaa, 0x3d, 0x3d, 0x25, 0x76,
	0x38, 0x05, 0x3e, 0x3d, 0xa5, 0xd0, 0xdf, 0xb0, 0xc0, 0x37, 0xf7, 0x52, 0x74, 0x11, 0xa2, 0x3e,
	0x34, 0x82, 0xe9, 0x17, 0xea, 0x70, 0xb3, 0x3e, 0xa8, 0x0d, 0xdb, 0xb6, 0x8a, 0xf0, 0x00, 0x20,
	0x56, 0x36, 0x21, 0x7c, 0x21, 0x8e, 0x25, 0x24, 0x7c, 0x91, 0x1c, 0x8b, 0xf8, 0xc6, 0xdf, 0x0c,
	0xe8, 0xaa, 0x66, 0x5e, 0xfa, 0x3c, 0xba, 0xca, 0x0b, 0x35, 0xae, 0x15, 0x5a, 0x2d, 0x0a, 0x3d,
	0x06, 0x98, 0x4a, 0x5a, 0xad, 0x13, 0x2d, 0x83, 0x2c, 0x68, 0x45, 0x34, 0xf4, 0x88, 0x43, 0x99,
	0xea, 0x24, 0x8d, 0x71, 0x0f, 0xd0, 0x85, 0xcb, 0xb8, 0xba, 0x4a, 0x9b, 0x7e, 0x5d, 0x53, 0xc6,
	0xf1, 0x03, 0x38, 0x18, 0xd3, 0x5c, 0xb2, 0x74, 0x0a, 0x16, 0xb0, 0x3f, 0xa6, 0x3c, 0x6e, 0x3a,
	0xd9, 0x67, 0x42, 0x33, 0x5c, 0xce, 0xf5, 0x5b, 0x51, 0xe1, 0x6f, 0xb4, 0xa2, 0xdd, 0x68, 0x2d,
	0x3b, 0x92, 0x1e, 0xf4, 0x52, 0x26, 0x71, 0xbc, 0x7f, 0x97, 0xed, 0x23, 0x1c, 0xa5, 0x6c, 0xaf,
	0xfd, 0x64, 0x68, 0xff, 0x9c, 0x12, 0x3f, 0x95, 0xc0, 0xcf, 0x3d, 0xcf, 0x8e, 0x6f, 0x60, 0x45,
	0x7d, 0xce, 0x34, 0xe0, 0xf2, 0x79, 0xc6, 0x2b, 0x38, 0x1c, 0x53, 0xae, 0xd5, 0x5c, 0x5b, 0xa2,
	0xab, 0xac, 0xfe, 0x52, 0x65, 0x71, 0xf4, 0x31, 0x87, 0x7e, 0xac, 0x72, 0x12, 0x05, 0x1b, 0x77,
	0x46, 0xa3, 0x54, 0x62, 0x0f, 0xea, 0xf3, 0x28, 0x58, 0x87, 0x8a, 0x2d, 0x0e, 0x04, 0xd7, 0x86,
	0x46, 0xcc, 0x0d, 0xfc, 0x84, 0x4b, 0x85, 0x62, 0x68, 0x96, 0xae, 0x3f, 0x53, 0x24, 0xf2, 0x5b,
	0xd8, 0x27, 0xf4, 0xd6, 0x11, 0xf1, 0xd4, 0x34, 0xaa, 0x08, 0x5f, 0xca, 0xb3, 0xb9, 0x20, 0x9c,
	0x32, 0xfe, 0x1f, 0x88, 0xcf, 0xe3, 0xb7, 0x26, 0x61, 0xfe, 0x07, 0xc4, 0x27, 0x3f, 0xea, 0xd0,
	0xb2, 0xd5, 0xc3, 0x8d, 0x4e, 0xa1, 0xab, 0x59, 0x91, 0xa1, 0x3b, 0xf2, 0xc1, 0x2c, 0xba, 0xd3,
	0xda, 0x97, 0x0b, 0xda, 0x03, 0x8d, 0x2b, 0x0f, 0x0d, 0xf4, 0x04, 0x60, 0xeb, 0x59, 0xd4, 0x97,
	0x7b, 0x0a, 0x26, 0xb6, 0xba, 0x7a, 0x2d, 0xae, 0xa0, 0x47, 0xd0, 0x4e, 0x07, 0x1d, 0x1d, 0x26,
	0x45, 0x19, 0x43, 0x5b, 0x1d, 0x99, 0x8e, 0x73, 0xb8, 0x82, 0x4e, 0xe1, 0x46, 0xc6, 0x89, 0xe8,
	0x28, 0x5b, 0xa6, 0xb9, 0xd3, 0xba, 0xa5, 0x95, 0x8a, 0x3c, 0xae, 0xa0, 0x73, 0xb8, 0x9d, 0x6e,
	0x7d, 0x15, 0x44, 0xc9, 0x0f, 0xd4, 0x71, 0x16, 0x24, 0x6f, 0xba, 0xbc, 0x88, 0x0f, 0x70, 0x6f,
	0x4c, 0xb9, 0xf6, 0x94, 0xba, 0x94, 0xbd, 0x5f, 0x90, 0xc4, 0x22, 0x5b, 0xb8, 0x72, 0xab, 0x59,
	0x07, 0xfa, 0xaf, 0x91, 0x7c, 0x8a, 0xe5, 0x21, 0x9e, 0x49, 0x9f, 0xc5, 0x2c, 0x1a, 0x1c, 0x43,
	0x56, 0x82, 0x57, 0xf4, 0x60, 0x5e, 0x9a, 0xbd, 0x43, 0x9a, 0x1a, 0x2c, 0x74, 0x57, 0x93, 0x96,
	0x1f, 0xf3, 0x5d, 0xba, 0x3e, 0x01, 0x4e, 0xad, 0xb1, 0x1b, 0x39, 0x6d, 0xba, 0xdc, 0x43, 0xbb,
	0xc0, 0xdf, 0x4a, 0xc1, 0x6a, 0xfc, 0xb7, 0xbd, 0xab, 0x72, 0xb6, 0x85, 0x2d, 0x77, 0x48, 0xae,
	0xff, 0x69, 0x43, 0xfe, 0x03, 0x79, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0x59, 0x5f, 0x52, 0x99,
	0x93, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	ListPackages(ctx context.Context, in *ListPackageRequest, opts ...grpc.CallOption) (Registry_ListPackagesClient, error)
	GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*Package, error)
	GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetBundlePath(ctx context.Context, in *GetBundlePathRequest, opts ...grpc.CallOption) (*BundlePath, error)
	GetBundleForChannel(ctx context.Context, in *GetBundleInChannelRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetChannelEntriesThatReplace(ctx context.Context, in *GetAllReplacementsRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatReplaceClient, error)
	GetBundleThatReplaces(ctx context.Context, in *GetReplacementRequest, opts ...grpc.CallOption) (*Bundle, error)
	GetChannelEntriesThatProvide(ctx context.Context, in *GetAllProvidersRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatProvideClient, error)
	GetLatestChannelEntriesThatProvide(ctx context.Context, in *GetLatestProvidersRequest, opts ...grpc.CallOption) (Registry_GetLatestChannelEntriesThatProvideClient, error)
	GetDefaultBundleThatProvides(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*Bundle, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) ListPackages(ctx context.Context, in *ListPackageRequest, opts ...grpc.CallOption) (Registry_ListPackagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[0], "/api.Registry/ListPackages", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryListPackagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_ListPackagesClient interface {
	Recv() (*PackageName, error)
	grpc.ClientStream
}

type registryListPackagesClient struct {
	grpc.ClientStream
}

func (x *registryListPackagesClient) Recv() (*PackageName, error) {
	m := new(PackageName)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*Package, error) {
	out := new(Package)
	err := c.cc.Invoke(ctx, "/api.Registry/GetPackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/api.Registry/GetBundle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetBundlePath(ctx context.Context, in *GetBundlePathRequest, opts ...grpc.CallOption) (*BundlePath, error) {
	out := new(BundlePath)
	err := c.cc.Invoke(ctx, "/api.Registry/GetBundlePath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetBundleForChannel(ctx context.Context, in *GetBundleInChannelRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/api.Registry/GetBundleForChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetChannelEntriesThatReplace(ctx context.Context, in *GetAllReplacementsRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatReplaceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[1], "/api.Registry/GetChannelEntriesThatReplace", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetChannelEntriesThatReplaceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetChannelEntriesThatReplaceClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetChannelEntriesThatReplaceClient struct {
	grpc.ClientStream
}

func (x *registryGetChannelEntriesThatReplaceClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetBundleThatReplaces(ctx context.Context, in *GetReplacementRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/api.Registry/GetBundleThatReplaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetChannelEntriesThatProvide(ctx context.Context, in *GetAllProvidersRequest, opts ...grpc.CallOption) (Registry_GetChannelEntriesThatProvideClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[2], "/api.Registry/GetChannelEntriesThatProvide", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetChannelEntriesThatProvideClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetChannelEntriesThatProvideClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetChannelEntriesThatProvideClient struct {
	grpc.ClientStream
}

func (x *registryGetChannelEntriesThatProvideClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetLatestChannelEntriesThatProvide(ctx context.Context, in *GetLatestProvidersRequest, opts ...grpc.CallOption) (Registry_GetLatestChannelEntriesThatProvideClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[3], "/api.Registry/GetLatestChannelEntriesThatProvide", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetLatestChannelEntriesThatProvideClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetLatestChannelEntriesThatProvideClient interface {
	Recv() (*ChannelEntry, error)
	grpc.ClientStream
}

type registryGetLatestChannelEntriesThatProvideClient struct {
	grpc.ClientStream
}

func (x *registryGetLatestChannelEntriesThatProvideClient) Recv() (*ChannelEntry, error) {
	m := new(ChannelEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) GetDefaultBundleThatProvides(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/api.Registry/GetDefaultBundleThatProvides", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	ListPackages(*ListPackageRequest, Registry_ListPackagesServer) error
	GetPackage(context.Context, *GetPackageRequest) (*Package, error)
	GetBundle(context.Context, *GetBundleRequest) (*Bundle, error)
	GetBundlePath(context.Context, *GetBundlePathRequest) (*BundlePath, error)
	GetBundleForChannel(context.Context, *GetBundleInChannelRequest) (*Bundle, error)
	GetChannelEntriesThatReplace(*GetAllReplacementsRequest, Registry_GetChannelEntriesThatReplaceServer) error
	GetBundleThatReplaces(context.Context, *GetReplacementRequest) (*Bundle, error)
	GetChannelEntriesThatProvide(*GetAllProvidersRequest, Registry_GetChannelEntriesThatProvideServer) error
	GetLatestChannelEntriesThatProvide(*GetLatestProvidersRequest, Registry_GetLatestChannelEntriesThatProvideServer) error
	GetDefaultBundleThatProvides(context.Context, *GetDefaultProviderRequest) (*Bundle, error)
}

// UnimplementedRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (*UnimplementedRegistryServer) ListPackages(req *ListPackageRequest, srv Registry_ListPackagesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListPackages not implemented")
}
func (*UnimplementedRegistryServer) GetPackage(ctx context.Context, req *GetPackageRequest) (*Package, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackage not implemented")
}
func (*UnimplementedRegistryServer) GetBundle(ctx context.Context, req *GetBundleRequest) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundle not implemented")
}
func (*UnimplementedRegistryServer) GetBundlePath(ctx context.Context, req *GetBundlePathRequest) (*BundlePath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundlePath not implemented")
}
func (*UnimplementedRegistryServer) GetBundleForChannel(ctx context.Context, req *GetBundleInChannelRequest) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundleForChannel not implemented")
}
func (*UnimplementedRegistryServer) GetChannelEntriesThatReplace(req *GetAllReplacementsRequest, srv Registry_GetChannelEntriesThatReplaceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChannelEntriesThatReplace not implemented")
}
func (*UnimplementedRegistryServer) GetBundleThatReplaces(ctx context.Context, req *GetReplacementRequest) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundleThatReplaces not implemented")
}
func (*UnimplementedRegistryServer) GetChannelEntriesThatProvide(req *GetAllProvidersRequest, srv Registry_GetChannelEntriesThatProvideServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChannelEntriesThatProvide not implemented")
}
func (*UnimplementedRegistryServer) GetLatestChannelEntriesThatProvide(req *GetLatestProvidersRequest, srv Registry_GetLatestChannelEntriesThatProvideServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLatestChannelEntriesThatProvide not implemented")
}
func (*UnimplementedRegistryServer) GetDefaultBundleThatProvides(ctx context.Context, req *GetDefaultProviderRequest) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultBundleThatProvides not implemented")
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_ListPackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).ListPackages(m, &registryListPackagesServer{stream})
}

type Registry_ListPackagesServer interface {
	Send(*PackageName) error
	grpc.ServerStream
}

type registryListPackagesServer struct {
	grpc.ServerStream
}

func (x *registryListPackagesServer) Send(m *PackageName) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetPackage(ctx, req.(*GetPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundle(ctx, req.(*GetBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetBundlePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundlePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundlePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundlePath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundlePath(ctx, req.(*GetBundlePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetBundleForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleInChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundleForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundleForChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundleForChannel(ctx, req.(*GetBundleInChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetChannelEntriesThatReplace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllReplacementsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetChannelEntriesThatReplace(m, &registryGetChannelEntriesThatReplaceServer{stream})
}

type Registry_GetChannelEntriesThatReplaceServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetChannelEntriesThatReplaceServer struct {
	grpc.ServerStream
}

func (x *registryGetChannelEntriesThatReplaceServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetBundleThatReplaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBundleThatReplaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetBundleThatReplaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBundleThatReplaces(ctx, req.(*GetReplacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetChannelEntriesThatProvide_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllProvidersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetChannelEntriesThatProvide(m, &registryGetChannelEntriesThatProvideServer{stream})
}

type Registry_GetChannelEntriesThatProvideServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetChannelEntriesThatProvideServer struct {
	grpc.ServerStream
}

func (x *registryGetChannelEntriesThatProvideServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetLatestChannelEntriesThatProvide_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestProvidersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetLatestChannelEntriesThatProvide(m, &registryGetLatestChannelEntriesThatProvideServer{stream})
}

type Registry_GetLatestChannelEntriesThatProvideServer interface {
	Send(*ChannelEntry) error
	grpc.ServerStream
}

type registryGetLatestChannelEntriesThatProvideServer struct {
	grpc.ServerStream
}

func (x *registryGetLatestChannelEntriesThatProvideServer) Send(m *ChannelEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_GetDefaultBundleThatProvides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetDefaultBundleThatProvides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Registry/GetDefaultBundleThatProvides",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetDefaultBundleThatProvides(ctx, req.(*GetDefaultProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPackage",
			Handler:    _Registry_GetPackage_Handler,
		},
		{
			MethodName: "GetBundle",
			Handler:    _Registry_GetBundle_Handler,
		},
		{
			MethodName: "GetBundlePath",
			Handler:    _Registry_GetBundlePath_Handler,
		},
		{
			MethodName: "GetBundleForChannel",
			Handler:    _Registry_GetBundleForChannel_Handler,
		},
		{
			MethodName: "GetBundleThatReplaces",
			Handler:    _Registry_GetBundleThatReplaces_Handler,
		},
		{
			MethodName: "GetDefaultBundleThatProvides",
			Handler:    _Registry_GetDefaultBundleThatProvides_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPackages",
			Handler:       _Registry_ListPackages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChannelEntriesThatReplace",
			Handler:       _Registry_GetChannelEntriesThatReplace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChannelEntriesThatProvide",
			Handler:       _Registry_GetChannelEntriesThatProvide_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLatestChannelEntriesThatProvide",
			Handler:       _Registry_GetLatestChannelEntriesThatProvide_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "registry.proto",
}
