// Code generated by go-bindata.
// sources:
// pkg/sqlite/db_migrations/201909251211_initialize_version.down.sql
// pkg/sqlite/db_migrations/201909251211_initialize_version.up.sql
// DO NOT EDIT!

package sqlite

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _pkgSqliteDb_migrations201909251211_initialize_versionDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xd2\xd7\x52\xf0\xcc\xcb\x2c\xc9\x4c\xcc\xc9\xac\x4a\x55\x28\xc9\x48\x55\x48\x49\x2c\x49\x4c\x4a\x2c\x4e\x55\x28\x4b\x2d\x2a\xce\xcc\xcf\x53\xd0\xd2\x07\x04\x00\x00\xff\xff\x83\xf4\xb1\x73\x25\x00\x00\x00")

func pkgSqliteDb_migrations201909251211_initialize_versionDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_pkgSqliteDb_migrations201909251211_initialize_versionDownSql,
		"pkg/sqlite/db_migrations/201909251211_initialize_version.down.sql",
	)
}

func pkgSqliteDb_migrations201909251211_initialize_versionDownSql() (*asset, error) {
	bytes, err := pkgSqliteDb_migrations201909251211_initialize_versionDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "pkg/sqlite/db_migrations/201909251211_initialize_version.down.sql", size: 37, mode: os.FileMode(436), modTime: time.Unix(1570128920, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _pkgSqliteDb_migrations201909251211_initialize_versionUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xd2\xd7\x52\xf0\xcc\xcb\x2c\xc9\x4c\xcc\xc9\xac\x4a\x55\x28\xc9\x48\x55\x48\x49\x2c\x49\x4c\x4a\x2c\x4e\x55\x28\x4b\x2d\x2a\xce\xcc\xcf\x53\xd0\xd2\x07\x04\x00\x00\xff\xff\x83\xf4\xb1\x73\x25\x00\x00\x00")

func pkgSqliteDb_migrations201909251211_initialize_versionUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_pkgSqliteDb_migrations201909251211_initialize_versionUpSql,
		"pkg/sqlite/db_migrations/201909251211_initialize_version.up.sql",
	)
}

func pkgSqliteDb_migrations201909251211_initialize_versionUpSql() (*asset, error) {
	bytes, err := pkgSqliteDb_migrations201909251211_initialize_versionUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "pkg/sqlite/db_migrations/201909251211_initialize_version.up.sql", size: 37, mode: os.FileMode(436), modTime: time.Unix(1570128920, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"pkg/sqlite/db_migrations/201909251211_initialize_version.down.sql": pkgSqliteDb_migrations201909251211_initialize_versionDownSql,
	"pkg/sqlite/db_migrations/201909251211_initialize_version.up.sql": pkgSqliteDb_migrations201909251211_initialize_versionUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"pkg": &bintree{nil, map[string]*bintree{
		"sqlite": &bintree{nil, map[string]*bintree{
			"db_migrations": &bintree{nil, map[string]*bintree{
				"201909251211_initialize_version.down.sql": &bintree{pkgSqliteDb_migrations201909251211_initialize_versionDownSql, map[string]*bintree{}},
				"201909251211_initialize_version.up.sql": &bintree{pkgSqliteDb_migrations201909251211_initialize_versionUpSql, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

