// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: health.proto

package grpc_health_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RegistryHealth_Check_FullMethodName = "/grpc.health.v1.RegistryHealth/Check"
)

// RegistryHealthClient is the client API for RegistryHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryHealthClient interface {
	Check(ctx context.Context, in *RegistryHealthCheckRequest, opts ...grpc.CallOption) (*RegistryHealthCheckResponse, error)
}

type registryHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryHealthClient(cc grpc.ClientConnInterface) RegistryHealthClient {
	return &registryHealthClient{cc}
}

func (c *registryHealthClient) Check(ctx context.Context, in *RegistryHealthCheckRequest, opts ...grpc.CallOption) (*RegistryHealthCheckResponse, error) {
	out := new(RegistryHealthCheckResponse)
	err := c.cc.Invoke(ctx, RegistryHealth_Check_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryHealthServer is the server API for RegistryHealth service.
// All implementations must embed UnimplementedRegistryHealthServer
// for forward compatibility
type RegistryHealthServer interface {
	Check(context.Context, *RegistryHealthCheckRequest) (*RegistryHealthCheckResponse, error)
	mustEmbedUnimplementedRegistryHealthServer()
}

// UnimplementedRegistryHealthServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryHealthServer struct {
}

func (UnimplementedRegistryHealthServer) Check(context.Context, *RegistryHealthCheckRequest) (*RegistryHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedRegistryHealthServer) mustEmbedUnimplementedRegistryHealthServer() {}

// UnsafeRegistryHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryHealthServer will
// result in compilation errors.
type UnsafeRegistryHealthServer interface {
	mustEmbedUnimplementedRegistryHealthServer()
}

func RegisterRegistryHealthServer(s grpc.ServiceRegistrar, srv RegistryHealthServer) {
	s.RegisterService(&RegistryHealth_ServiceDesc, srv)
}

func _RegistryHealth_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryHealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryHealth_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryHealthServer).Check(ctx, req.(*RegistryHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryHealth_ServiceDesc is the grpc.ServiceDesc for RegistryHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.health.v1.RegistryHealth",
	HandlerType: (*RegistryHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _RegistryHealth_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
